#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  filetree_direction = "left"
  default_indent = 2
  disabled_plugins = ["vim-import-js"]
  automatic_update = true
  lint_engine = "ale"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "incsearch"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

## fuzzy finder
[[layers]]
  name = "fzf"

## Languauge specific layers
[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"
  user_emmet_leader_key = "<C-e>"

[[layers]]
  name = "lang#java"
  format_on_save = true
  java_formatter_jar = "~/.SpaceVim.d/java/google-java-format-1.10.0-all-deps.jar"
  # java_file_head = [""]

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#python"
  python_interpreter = "~/.config/nvim/.venv/bin/python3"
  python_file_head = [""]
  # python_file_head = [
  #   '#!/usr/bin/env python3',
  #   '# -*- coding : utf-8 -*-'
  #   ''
  # ]

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#xml"

## lsp protocol
[[layers]]
  name = "lsp"
  filetypes=[
    "css",
    "dockerfile",
    # "java",
    "javascript",
    "html",
    "python",
    "sh",
    "typescript"
  ]


## Buggy built-in plugins work-around
[[custom_plugins]]
  repo = "BUGBOUNTYchrisg8691/vim-js-import"
  merged = false
